extern const GeoLayout rocket_obstacle_4_geo[];
extern Lights1 rocket_obstacle_4_f3dlite_material_039_layer1_lights;
extern u8 rocket_obstacle_4_iron_wall_ia8_i8[];
extern Vtx rocket_obstacle_4_Cylinder_002_mesh_layer_1_vtx_0[259];
extern Gfx rocket_obstacle_4_Cylinder_002_mesh_layer_1_tri_0[];
extern Gfx mat_rocket_obstacle_4_f3dlite_material_039_layer1[];
extern Gfx mat_revert_rocket_obstacle_4_f3dlite_material_039_layer1[];
extern Gfx rocket_obstacle_4_Cylinder_002_mesh_layer_1[];
extern Gfx rocket_obstacle_4_material_revert_render_settings[];
