extern const GeoLayout wood_crate_geo[];
extern Lights1 wood_crate_f3dlite_material_001_lights;
extern Lights1 wood_crate_f3dlite_material_002_lights;
extern u8 wood_crate_wood_crate_ia8_i8[];
extern u8 wood_crate_wood_crate_top_ia8_i8[];
extern Vtx wood_crate_particle_mesh_mesh_layer_1_vtx_0[16];
extern Gfx wood_crate_particle_mesh_mesh_layer_1_tri_0[];
extern Vtx wood_crate_particle_mesh_mesh_layer_1_vtx_1[8];
extern Gfx wood_crate_particle_mesh_mesh_layer_1_tri_1[];
extern Gfx mat_wood_crate_f3dlite_material_001[];
extern Gfx mat_wood_crate_f3dlite_material_002[];
extern Gfx wood_crate_particle_mesh_mesh_layer_1[];
extern Gfx wood_crate_material_revert_render_settings[];
