extern const GeoLayout iron_cage_geo[];
extern Lights1 iron_cage_f3dlite_material_001_lights;
extern Lights1 iron_cage_f3dlite_material_002_lights;
extern u8 iron_cage_cage_side_ia8_i8[];
extern u8 iron_cage_cage_top_ia8_i8[];
extern Vtx iron_cage_crate_mesh_mesh_layer_1_vtx_0[16];
extern Gfx iron_cage_crate_mesh_mesh_layer_1_tri_0[];
extern Vtx iron_cage_crate_mesh_mesh_layer_1_vtx_1[8];
extern Gfx iron_cage_crate_mesh_mesh_layer_1_tri_1[];
extern Gfx mat_iron_cage_f3dlite_material_001[];
extern Gfx mat_iron_cage_f3dlite_material_002[];
extern Gfx iron_cage_crate_mesh_mesh_layer_1[];
extern Gfx iron_cage_material_revert_render_settings[];
