#include "src/game/envfx_snow.h"

const GeoLayout kart_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 90, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kart_001_displaylist_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, kart_001_displaylist_mesh_layer_4),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -240, 277, 0, -41, -36, 138),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ASM(0, kartWheel),
						GEO_TRANSLATE_ROTATE(LAYER_ALPHA, 0, 0, 0, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, kart_002_displaylist_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -199, -94, 53, -90, 0, 180),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ASM(1, kartWheel),
						GEO_TRANSLATE_ROTATE(LAYER_ALPHA, 0, 0, 0, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ASM(5, kartWheel),
							GEO_TRANSLATE_ROTATE(LAYER_ALPHA, 0, 0, 0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kart_003_wheel1_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -199, -94, -53, -90, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ASM(2, kartWheel),
						GEO_TRANSLATE_ROTATE(LAYER_ALPHA, 0, 0, 0, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ASM(6, kartWheel),
							GEO_TRANSLATE_ROTATE(LAYER_ALPHA, 0, 0, 0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kart_004_wheel2_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 254, -94, 53, -90, 0, 180),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ASM(3, kartWheel),
						GEO_TRANSLATE_ROTATE(LAYER_ALPHA, 0, 0, 0, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kart_005_wheel3_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 254, -94, -53, -90, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ASM(4, kartWheel),
						GEO_TRANSLATE_ROTATE(LAYER_ALPHA, 0, 0, 0, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kart_006_wheel4_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kart_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kart_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
