extern const GeoLayout pss_area_1_geo[];
extern const GeoLayout pss_area_1[];
extern const Collision pss_area_1_collision[];
extern const MacroObject pss_area_1_macro_objs[];
extern Lights1 pss_dl_f3dlite_material_lights;
extern Lights1 pss_dl_f3dlite_material_006_lights;
extern Lights1 pss_dl_f3dlite_material_001_lights;
extern Lights1 pss_dl_f3dlite_material_012_lights;
extern u8 pss_dl_wf_textures_04000_rgba16_ci8[];
extern u8 pss_dl_wf_textures_04000_rgba16_pal_rgba16[];
extern u8 pss_dl_hmc_textures_09800_rgba16_ci8[];
extern u8 pss_dl_hmc_textures_09800_rgba16_pal_rgba16[];
extern u8 pss_dl_hmc_textures_07800_rgba16_ci8[];
extern u8 pss_dl_hmc_textures_07800_rgba16_pal_rgba16[];
extern u8 pss_dl_bob_textures_08000_rgba16_ci8[];
extern u8 pss_dl_bob_textures_08000_rgba16_pal_rgba16[];
extern Vtx pss_dl_NurbsCurve_mesh_layer_1_vtx_0[488];
extern Gfx pss_dl_NurbsCurve_mesh_layer_1_tri_0[];
extern Vtx pss_dl_Plane_mesh_layer_1_vtx_0[72];
extern Gfx pss_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx pss_dl_Plane_mesh_layer_1_vtx_1[36];
extern Gfx pss_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx pss_dl_Plane_mesh_layer_1_vtx_2[24];
extern Gfx pss_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx pss_dl_Plane_mesh_layer_1_vtx_3[328];
extern Gfx pss_dl_Plane_mesh_layer_1_tri_3[];
extern Vtx pss_dl_Plane_001_mesh_layer_1_vtx_0[272];
extern Gfx pss_dl_Plane_001_mesh_layer_1_tri_0[];
extern Gfx mat_pss_dl_f3dlite_material[];
extern Gfx mat_revert_pss_dl_f3dlite_material[];
extern Gfx mat_pss_dl_f3dlite_material_006[];
extern Gfx mat_revert_pss_dl_f3dlite_material_006[];
extern Gfx mat_pss_dl_f3dlite_material_002[];
extern Gfx mat_revert_pss_dl_f3dlite_material_002[];
extern Gfx mat_pss_dl_f3dlite_material_001[];
extern Gfx mat_revert_pss_dl_f3dlite_material_001[];
extern Gfx mat_pss_dl_f3dlite_material_003[];
extern Gfx mat_revert_pss_dl_f3dlite_material_003[];
extern Gfx mat_pss_dl_f3dlite_material_012[];
extern Gfx pss_dl_NurbsCurve_mesh_layer_1[];
extern Gfx pss_dl_Plane_mesh_layer_1[];
extern Gfx pss_dl_Plane_001_mesh_layer_1[];
extern Gfx pss_dl_material_revert_render_settings[];
